version: "2.1"
services:
  api:
    build: .
    ports: 
    - "8888:8080"
  db: 
    image: neo4j:latest
    environment:
      NEO4J_AUTH: neo4j/test
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
    ports:
    - "7464:7474"
    - "7687:7687"